namespace SuperariLife.Common.Helpers
{
    public class Constants
    {
 
        public const string AccessControlAllowOrigin = "*";
        public const string AdminMailPath = "wwwroot\\EmailTemplates";
        public const string AdminPasswordEmail = "AdminPassword.html";
        public const string AutoGeneratedPassword = "AutoGeneratedPassword.html";
        public const string RewardCouponCode = "RewardCouponCode.html";
        public const string ContactUs = "ContactUs.html";
        public const string ContentTypeJson = "application/json";
        public const string EmailTemplate = "wwwroot\\EmailTemplates";
        public const string ExceptionReport = "ExceptionReport.html";
        public const string ForgetPasswordEmailtem = "UserForgotPassword.html";
        public const string ImagePath = "EmailTemplates/images";
        public const string LogsFilePathException = "Logs/ExceptionLogs";
        public const string LogsFilePathRequest = "Logs/RequestLogs";
        public const string QueryStringParams = "Query String Params: ";
        public const string RequestMessage = "Message: ";
        public const string RequestModel = "requestModel";
        public const string RequestParams = "Request Params: ";
        public const string https = "https://";

    }
}
